[package]
name = "tb-knowledge"
version = "0.1.0"
edition = "2021"

[dependencies]
brain-client = { git = "https://github.com/EarlySalty/Deadlock-Brain.git", rev = "54dcae30a172f5cccdb9f53b6bd6ed746f9315ec" }
tokio = { workspace = true }

regex     = { workspace = true }
thiserror = { workspace = true }
