[package]
name = "tb-knowledge"
version = "0.1.0"
edition = "2021"

[dependencies]
brain-client = { git = "https://github.com/EarlySalty/Deadlock-Brain.git", rev = "3b86d3cbe5ea39a67b8b1fbd8a3d48ab935982ef" }
tokio = { workspace = true }

regex     = { workspace = true }
thiserror = { workspace = true }
