[package]
name = "tb-knowledge"
version = "0.1.0"
edition = "2021"

[dependencies]
brain-client = { git = "https://github.com/EarlySalty/Deadlock-Brain.git", rev = "bdcc6dec3424bd313d36e5f545de2a07df564c7f" }
tokio = { workspace = true }

regex     = { workspace = true }
thiserror = { workspace = true }
