[package]
name = "tb-config"
version = "0.1.0"
edition.workspace = true

[features]
default = []
inventory = ["dep:syn", "dep:proc-macro2", "dep:quote"]

[[bin]]
name = "tb-config-inventory"
path = "src/bin/tb-config-inventory.rs"
required-features = ["inventory"]

[dependencies]
syn = { version = "3", features = ["full", "visit"], optional = true }
proc-macro2 = { version = "1", features = ["span-locations"], optional = true }
quote = { version = "1", optional = true }
tb-error = { workspace = true }
tracing  = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { version = "0.8.23", default-features = false, features = ["parse", "display"] }
toml_edit = { version = "0.22.27", default-features = false, features = ["parse", "display"] }
url = { workspace = true }
libc = "0.2"
sha2 = { workspace = true }
