//! AUTO-GENERIERT aus bot/analytics/api_chat_deep.py via rust/scripts/extract_chat_lexicon.py.
//! Keyword-Listen fuer chat-content-analysis (exakte Daten-Paritaet, kein Abtippen).
//! Bei Aenderung der Python-Listen neu generieren.

pub const ALIAS_TO_HERO: &[(&str, &str)] = &[
    ("abrams", "abrams"),
    ("bebop", "bebop"),
    ("dynamo", "dynamo"),
    ("grey talon", "grey_talon"),
    ("talon", "grey_talon"),
    ("gt", "grey_talon"),
    ("haze", "haze"),
    ("infernus", "infernus"),
    ("inf", "infernus"),
    ("ivy", "ivy"),
    ("kelvin", "kelvin"),
    ("lady geist", "lady_geist"),
    ("geist", "lady_geist"),
    ("lash", "lash"),
    ("mcginnis", "mcginnis"),
    ("mirage", "mirage"),
    ("mo and krill", "mo_krill"),
    ("mo & krill", "mo_krill"),
    ("mo krill", "mo_krill"),
    ("mokrill", "mo_krill"),
    ("paradox", "paradox"),
    ("pocket", "pocket"),
    ("seven", "seven"),
    ("shiv", "shiv"),
    ("vindicta", "vindicta"),
    ("vindi", "vindicta"),
    ("viscous", "viscous"),
    ("warden", "warden"),
    ("wraith", "wraith"),
    ("yamato", "yamato"),
    ("yama", "yamato"),
    ("calico", "calico"),
    ("holliday", "holliday"),
    ("holiday", "holliday"),
    ("apollo", "apollo"),
    ("billy", "billy"),
    ("celeste", "celeste"),
    ("doorman", "doorman"),
    ("drifter", "drifter"),
    ("graves", "graves"),
    ("mina", "mina"),
    ("paige", "paige"),
    ("rem", "rem"),
    ("silver", "silver"),
    ("sinclair", "sinclair"),
    ("venator", "venator"),
    ("victor", "victor"),
    ("vyper", "vyper"),
    ("viper", "vyper"),
];

pub const TOPIC_KEYWORDS: &[(&str, &[&str])] = &[
    (
        "builds",
        &[
            "build",
            "item",
            "weapon",
            "spirit",
            "vitality",
            "flex slot",
            "tesla",
            "headshot",
            "lifestrike",
            "majestic",
            "mystic",
            "soul",
            "ability",
            "active item",
            "component",
            "upgrade",
        ] as &[&str],
    ),
    (
        "ranked",
        &[
            "rank",
            "mmr",
            "elo",
            "ranked",
            "competitive",
            "placement",
            "rank up",
            "derank",
            "initiate",
            "seeker",
            "alchemist",
            "arcanist",
            "ritualist",
            "emissary",
            "archon",
            "oracle",
            "phantom",
            "ascendant",
            "eternus",
        ] as &[&str],
    ),
    (
        "meta",
        &[
            "meta",
            "nerf",
            "buff",
            "patch",
            "broken",
            "op",
            "overpowered",
            "underpowered",
            "rework",
            "hotfix",
            "s-tier",
            "s tier",
            "a-tier",
            "comp",
            "balance",
            "update",
            "changelog",
            "patchnotes",
        ] as &[&str],
    ),
    (
        "gameplay",
        &[
            "push", "gank", "lane", "jungle", "tower", "urn", "soul orb", "mid boss", "patron",
            "guardian", "walker", "rejuv", "zipline", "teleport", "shrine", "flex", "last hit",
            "deny", "farm", "creep", "troop",
        ] as &[&str],
    ),
    (
        "backseat",
        &[
            "you should",
            "you need to",
            "just buy",
            "just play",
            "just pick",
            "pick him",
            "pick her",
            "don't buy",
            "don't pick",
            "don't play",
            "play safe",
            "play aggressive",
            "go left",
            "go right",
            "go back",
            "buy this",
            "try this",
            "swap to",
            "switch to",
            "sell that",
            "why didn't you",
            "why don't you",
            "you could have",
            "should have",
            "shouldve",
            "shoulda",
            "kauf",
            "nimm",
            "spiel",
            "geh",
            "mach",
            "probier",
            "du musst",
            "du solltest",
            "warum kaufst",
            "warum spielst",
            "hättest du",
            "kauf dir",
            "nimm dir",
            "versuch mal",
            "spiel mal",
            "geh mal",
            "nicht kaufen",
            "nicht spielen",
            "hör auf",
            "lass das",
        ] as &[&str],
    ),
];

pub const REACTION_TOKENS: &[&str] = &[
    "banger",
    "catjam",
    "cheerstothat",
    "crazy",
    "damn",
    "geil",
    "gg",
    "ggs",
    "haha",
    "hahaha",
    "heyguys",
    "huh",
    "hype",
    "insane",
    "kappa",
    "kekw",
    "krass",
    "letsgo",
    "lmao",
    "lol",
    "lul",
    "nah",
    "nice",
    "notlikethis",
    "omg",
    "peepo",
    "pog",
    "pogchamp",
    "poggers",
    "rip",
    "sadge",
    "safe",
    "shruge",
    "uff",
    "woah",
    "wow",
    "wp",
    "wtf",
    "xd",
    "xdd",
];

pub const SMALLTALK_TOKENS: &[&str] = &[
    "achso", "ah", "check", "doch", "genau", "ja", "jaa", "jaaa", "jo", "klar", "man", "mhm", "na",
    "ne", "nein", "no", "nö", "oh", "oha", "ok", "okay", "same", "stark", "stimmt", "sure", "true",
    "wieder", "yep", "yes", "zusammen",
];

pub const GREETING_TOKENS: &[&str] = &[
    "abend", "back", "bye", "gn8", "hallo", "hello", "hey", "hi", "huhu", "moin", "moooin",
    "nabend", "nacht", "o7", "servus", "wb",
];

pub const POSITIVE_WORDS: &[&str] = &[
    "alter",
    "amazing",
    "banger",
    "based",
    "beautiful",
    "bombe",
    "bruder",
    "carry",
    "catjam",
    "chad",
    "clean",
    "clutch",
    "cracked",
    "danke",
    "diff",
    "digga",
    "dope",
    "ehre",
    "ehrenmann",
    "feelsgood",
    "fire",
    "geil",
    "genial",
    "gg",
    "gigachad",
    "goat",
    "godlike",
    "gott",
    "gönnung",
    "hammer",
    "hearts",
    "heftig",
    "huge",
    "hype",
    "ily",
    "incredible",
    "insane",
    "jebaited",
    "kappa",
    "king",
    "krass",
    "kreygasm",
    "legendary",
    "legende",
    "letsgo",
    "liebe",
    "lit",
    "love",
    "mega",
    "mvp",
    "nice",
    "outplay",
    "outplayed",
    "peped",
    "pepejam",
    "perfect",
    "pog",
    "pogchamp",
    "poggers",
    "pogu",
    "queen",
    "sick",
    "stark",
    "super",
    "thanks",
    "thx",
    "trihard",
    "wahnsinn",
    "widepeepo",
    "wp",
];

pub const NEGATIVE_WORDS: &[&str] = &[
    "afk",
    "asozial",
    "awful",
    "bad",
    "behindert",
    "boring",
    "bot",
    "braindead",
    "broken",
    "bugged",
    "cheater",
    "clown",
    "cope",
    "copium",
    "cringe",
    "disgusting",
    "dog",
    "dogwater",
    "dreck",
    "dumm",
    "ez",
    "feeder",
    "feeding",
    "garbage",
    "griefer",
    "griefing",
    "grottig",
    "hacker",
    "hasmods",
    "hate",
    "hurensohn",
    "inting",
    "kack",
    "kacke",
    "langweilig",
    "lost",
    "lächerlich",
    "malding",
    "mies",
    "mist",
    "müll",
    "nervig",
    "noob",
    "omegalul",
    "pathetic",
    "peinlich",
    "pepega",
    "ragequit",
    "ratio",
    "report",
    "salty",
    "scheisse",
    "schlecht",
    "schrott",
    "smurf",
    "smurfing",
    "spast",
    "terrible",
    "throw",
    "throwing",
    "tilted",
    "toxic",
    "trash",
    "troll",
    "unbalanced",
    "unfair",
    "useless",
    "washed",
    "weirdchamp",
    "worst",
    "yikes",
];

pub const SHORT_POSITIVE: &[&str] = &["dw", "gg", "w"];

pub const SHORT_NEGATIVE: &[&str] = &["f", "ff", "l", "nah"];

pub const BACKSEAT_PHRASES: &[&str] = &[
    "you should",
    "you need to",
    "just buy",
    "just play",
    "just pick",
    "don't buy",
    "don't pick",
    "play safe",
    "play aggressive",
    "why didn't you",
    "why don't you",
    "you could have",
    "should have",
    "shouldve",
    "du musst",
    "du solltest",
    "warum kaufst",
    "warum spielst",
    "hättest du",
    "kauf dir",
    "nimm dir",
    "versuch mal",
    "spiel mal",
    "geh mal",
    "nicht kaufen",
    "hör auf",
    "lass das",
];

pub const SOCIAL_MARKERS: &[&str] = &[
    "discord",
    "youtube",
    "tiktok",
    "instagram",
    "social",
    "follow",
    "abo",
    "sub",
    "community",
    "raid",
    "clip",
    "danke",
    "thanks",
    "thx",
];

pub const REACTION_PHRASES: &[&str] = &[
    "let's go",
    "lets go",
    "<3",
    ":d",
    ":(",
    ":o",
    "skill issue",
    "all good",
];

pub const EMOTE_PREFIXES: &[&str] = &[
    "dhalu", "frag", "peepo", "kitty", "owo", "uwu", "xdgara", "seems",
];

pub const EMOTE_SUFFIXES: &[&str] = &[
    "cheer", "hype", "love", "clap", "lul", "dance", "jam", "hug",
];

pub const GREETING_PHRASES: &[&str] = &[
    "guten morgen",
    "guten abend",
    "gute nacht",
    "bye bye",
    "wie läufts",
];

pub const POSITIVE_PHRASES: &[&str] = &[
    "lets go",
    "let's go",
    "gg wp",
    "well played",
    "so good",
    "so sick",
    "no way",
    "holy shit",
    "my goat",
    "too good",
    "what a play",
    "so clean",
    "big brain",
    "guter stream",
    "geiler stream",
    "macht spass",
    "feier ich",
];

pub const NEGATIVE_PHRASES: &[&str] = &[
    "so bad",
    "too bad",
    "skill issue",
    "get good",
    "git gud",
    "so boring",
    "dead game",
    "touch grass",
    "no shot",
    "kein skill",
    "macht keinen spass",
    "ist kaputt",
];
