[package]
name = "tb-engagement"
version = "0.1.0"
edition.workspace = true

[dependencies]
chrono     = { workspace = true }
regex      = { workspace = true }
reqwest    = { workspace = true }
serde_json = { workspace = true }
sqlx       = { workspace = true }

[dev-dependencies]
tokio    = { workspace = true, features = ["rt-multi-thread", "macros"] }
wiremock = { workspace = true }
