[package]
name = "tb-highlight"
version = "0.1.0"
edition.workspace = true

[dependencies]
reqwest     = { workspace = true }
serde_json  = { workspace = true }
tracing     = { workspace = true }
thiserror   = { workspace = true }
regex       = { workspace = true }
async-trait = { workspace = true }
chrono     = { workspace = true }
tokio      = { workspace = true, features = ["process", "time"] }
sqlx       = { workspace = true }
bzip2-rs   = "0.1"

[dev-dependencies]
tokio    = { workspace = true, features = ["rt-multi-thread", "macros"] }
wiremock = { workspace = true }
