-- Private Dashboard-Rückmeldungen; Rohtexte verlassen diese Tabellen nicht.
CREATE TABLE dashboard_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL CHECK (owner_id ~ '^[0-9]+$'),
    author_label TEXT NOT NULL,
    request_id TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('feedback', 'feature')),
    title TEXT NOT NULL CHECK (char_length(title) BETWEEN 3 AND 120),
    body TEXT NOT NULL CHECK (char_length(body) BETWEEN 10 AND 4000),
    area TEXT NOT NULL DEFAULT '' CHECK (char_length(area) <= 80),
    status TEXT NOT NULL DEFAULT 'received' CHECK (
        status IN ('received', 'reviewing', 'planned', 'in_progress', 'done', 'declined')
        OR (status = 'answered' AND kind = 'feedback')
    ),
    result_path TEXT,
    decision_reason TEXT CHECK (char_length(decision_reason) BETWEEN 3 AND 800),
    roadmap_id BIGINT REFERENCES twitch_roadmap_items(id) ON DELETE RESTRICT,
    duplicate_of BIGINT REFERENCES dashboard_feedback(id) ON DELETE RESTRICT,
    revision INTEGER NOT NULL DEFAULT 0,
    admin_read BOOLEAN NOT NULL DEFAULT FALSE,
    owner_seen_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_id, request_id),
    CHECK (duplicate_of IS NULL OR (duplicate_of <> id AND kind = 'feature')),
    CHECK (duplicate_of IS NULL OR roadmap_id IS NULL),
    CHECK (roadmap_id IS NULL OR (kind = 'feature' AND result_path IS NOT NULL)),
    CHECK (status <> 'done' OR result_path IS NOT NULL OR duplicate_of IS NOT NULL),
    CHECK (status <> 'declined' OR decision_reason IS NOT NULL OR duplicate_of IS NOT NULL)
);
CREATE INDEX dashboard_feedback_owner ON dashboard_feedback(owner_id, id DESC);
CREATE INDEX dashboard_feedback_owner_rate ON dashboard_feedback(owner_id, created_at DESC);
CREATE INDEX dashboard_feedback_new ON dashboard_feedback(id DESC) WHERE NOT admin_read;
CREATE INDEX dashboard_feedback_duplicate ON dashboard_feedback(duplicate_of) WHERE duplicate_of IS NOT NULL;
CREATE INDEX dashboard_feedback_roadmap ON dashboard_feedback(roadmap_id) WHERE roadmap_id IS NOT NULL;
CREATE TABLE dashboard_feedback_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_id BIGINT NOT NULL REFERENCES dashboard_feedback(id) ON DELETE CASCADE,
    request_id TEXT NOT NULL,
    request_payload JSONB NOT NULL,
    status TEXT NOT NULL,
    reply TEXT NOT NULL CHECK (char_length(reply) <= 4000),
    result_path TEXT,
    decision_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (feedback_id, request_id)
);
CREATE INDEX dashboard_feedback_events_history ON dashboard_feedback_events(feedback_id, id);
