-- Dashboard/content runtime-created tables now owned by migrations:
-- internal_home_changelog, twitch_roadmap_items, schema_version.

CREATE TABLE IF NOT EXISTS public.internal_home_changelog (
    id BIGSERIAL NOT NULL,
    entry_date DATE DEFAULT CURRENT_DATE NOT NULL,
    title TEXT DEFAULT ''::text NOT NULL,
    content TEXT DEFAULT ''::text NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT internal_home_changelog_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_internal_home_changelog_order
    ON public.internal_home_changelog USING btree (entry_date DESC, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.twitch_roadmap_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.twitch_roadmap_items_id_seq
    ) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'planned'::text NOT NULL,
    priority INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT twitch_roadmap_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.schema_version (
    component TEXT NOT NULL,
    version INTEGER NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    CONSTRAINT schema_version_pkey PRIMARY KEY (component)
);
