from __future__ import annotations

BETA_STEAM_ACCOUNT_ID = 1066648163
BETA_TWITCH_LOGIN = "earlysalty"
BETA_DISCORD_USER_ID = 662995601738170389
STATE_PATH = "data/highlight_clipper/state.json"
CLIPS_DIR = "data/highlight_clipper/clips"
POLL_INTERVAL_SECONDS = 600
CLIP_PADDING_SECONDS = 10
MULTIKILL_MIN_KILLS = 3
MULTIKILL_THRESHOLD_SECONDS = 10
TEAMFIGHT_MIN_KILLS = 4
TEAMFIGHT_THRESHOLD_SECONDS = 15
FFMPEG_PATH = "/home/naniadm/.local/bin/ffmpeg"
MAX_DISCORD_FILE_MB = 24
