from __future__ import annotations

HIGHLIGHT_DISCORD_CHANNEL_ID = 1374364800817303632
STATE_PATH = "data/highlight_clipper/state.json"
CLIPS_DIR = "data/highlight_clipper/clips"
POLL_INTERVAL_SECONDS = 600
CLIP_PADDING_SECONDS = 10
MULTIKILL_MIN_KILLS = 3
MULTIKILL_THRESHOLD_SECONDS = 10
TEAMFIGHT_MIN_KILLS = 4
TEAMFIGHT_THRESHOLD_SECONDS = 15
FFMPEG_PATH = "/usr/bin/ffmpeg"
MAX_DISCORD_FILE_MB = 24
