[package]
name = "tb-monitoring"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
chrono      = { workspace = true }
axum        = { workspace = true }
hex         = { workspace = true }
hmac        = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
sha2        = { workspace = true }
sqlx        = { workspace = true }
tokio       = { workspace = true, features = ["sync", "time"] }
tracing     = { workspace = true }
uuid                = { workspace = true }
tb-transport-twitch = { workspace = true }
