/* Run after generating dist/roadmap-history/index.html. Uses a loopback-only server. */
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';

const require = createRequire(new URL('../../.roadmap-test-runtime/package.json', import.meta.url));
const {chromium} = require('playwright');
const root = resolve(new URL('../..', import.meta.url).pathname);
const output = resolve(root, 'dist/roadmap-history');
const html = await readFile(resolve(output, 'index.html'));
const server = createServer((request, response) => {
  response.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'});
  response.end(html);
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const url = 'http://127.0.0.1:' + server.address().port + '/';
let browser;
const checks = [];
try {
  browser = await chromium.launch({headless: true});
  const page = await browser.newPage({viewport: {width: 1440, height: 1120}});
  const errors = [];
  page.on('pageerror', error => errors.push(String(error)));
  await page.goto(url);
  await page.locator('.milestone').first().waitFor();
  assert.ok(await page.locator('.feature-label').count() > 10);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  checks.push('Desktop: echte Historie gerendert, keine Seitenüberbreite');
  await page.screenshot({path: resolve(output, 'roadmap-desktop.png'), fullPage: true});
  await page.locator('#search').fill('Uplink');
  await page.waitForTimeout(240);
  assert.ok((await page.locator('#result-count').textContent()).includes('Änderungen'));
  await page.locator('.milestone').first().click();
  await page.locator('#detail[open]').waitFor();
  assert.equal(await page.locator('#detail-title').textContent(), 'Uplink & Encoding');
  assert.ok(await page.locator('.history-event a').count() > 0);
  await page.getByRole('button', {name: /Vollständige Entwicklung zeigen/}).click();
  assert.ok(await page.locator('.history-event').count() >= 40);
  await page.locator('.history-event details').first().locator('summary').click();
  assert.ok((await page.locator('.history-event details').first().textContent()).includes('Originaler Commit-Titel'));
  await page.screenshot({path: resolve(output, 'roadmap-detail.png'), fullPage: true});
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#detail').evaluate(d => d.open), false);
  checks.push('Monatskarte, vollständige Feature-Linie, Belege und Escape funktionieren');
  await page.getByRole('button', {name: 'Zurücksetzen', exact: true}).click();
  await page.getByRole('button', {name: 'Feature-Stammbaum', exact: true}).click();
  assert.ok(await page.locator('.family').count() >= 3);
  assert.ok(await page.locator('.feature-card').count() > 10);
  await page.screenshot({path: resolve(output, 'roadmap-tree.png'), fullPage: true});
  checks.push('Stammbaum mit Bereichen, Features und datierten Stationen');
  await page.getByRole('button', {name: 'Änderungsliste', exact: true}).click();
  assert.equal(await page.locator('.event-line').count(), 80);
  await page.getByRole('button', {name: /Weitere Änderungen laden/}).click();
  assert.equal(await page.locator('.event-line').count(), 160);
  checks.push('Änderungsliste und Pagination');
  await page.locator('#kind').selectOption('maintenance');
  assert.ok(await page.locator('.event-line').count() > 0);
  checks.push('Technik-Filter funktioniert unabhängig vom Checkbox-Standard');
  await page.locator('#search').fill('no-such-feature-abc-123');
  await page.waitForTimeout(240);
  assert.ok(await page.getByText('Keine passenden Änderungen', {exact: true}).isVisible());
  await page.getByRole('button', {name: 'Zurücksetzen', exact: true}).click();
  await page.locator('#period').selectOption('custom');
  await page.locator('#from').fill('2026-09-17');
  await page.locator('#to').fill('2026-08-01');
  await page.locator('#to').dispatchEvent('change');
  assert.ok(await page.getByText(/Das Startdatum liegt nach/).isVisible());
  checks.push('Leere Suche und ungültiger Datumsbereich');
  await page.goto(url + '?search=Uplink&view=tree&period=all&feature=uplink');
  await page.locator('#detail[open]').waitFor();
  assert.equal(await page.locator('#detail-title').textContent(), 'Uplink & Encoding');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#search').inputValue(), 'Uplink');
  checks.push('Direktlink stellt Filter, Ansicht und Feature wieder her');
  const mobile = await browser.newPage({viewport: {width: 390, height: 844}, isMobile: true, hasTouch: true});
  mobile.on('pageerror', error => errors.push(String(error)));
  await mobile.goto(url);
  await mobile.locator('.milestone').first().waitFor();
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await mobile.locator('.milestone').first().click();
  await mobile.locator('#close-detail').click();
  await mobile.getByRole('button', {name: 'Feature-Stammbaum', exact: true}).click();
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await mobile.screenshot({path: resolve(output, 'roadmap-mobile.png'), fullPage: true});
  checks.push('390px: keine Seitenüberbreite, Touch-Karten und Schließen bedienbar');
  assert.deepEqual(errors, []);
  checks.push('Keine JavaScript-Laufzeitfehler');
  console.log(JSON.stringify({passed: checks.length, checks, screenshots: output}, null, 2));
} finally {
  if (browser) await browser.close();
  await new Promise(resolve => server.close(resolve));
}
