//! Öffentlicher read-only Roadmap-Endpunkt für das React-Dashboard.

use axum::{extract::State, http::StatusCode, response::IntoResponse, Json};
use serde_json::json;
use sqlx::{PgPool, Row};

const ENSURE_TABLE_SQL: &str = r#"
CREATE TABLE IF NOT EXISTS twitch_roadmap_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT NOT NULL,
    description TEXT,
    status      TEXT NOT NULL DEFAULT 'planned',
    priority    INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
"#;

/// `GET /twitch/api/v2/roadmap`
pub async fn get_handler(State(pool): State<PgPool>) -> impl IntoResponse {
    if let Err(e) = sqlx::query(ENSURE_TABLE_SQL).execute(&pool).await {
        tracing::error!("roadmap Tabellenprüfung fehlgeschlagen: {e}");
        return (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({"error":"DB-Fehler"})),
        )
            .into_response();
    }

    let rows = sqlx::query(
        "SELECT id, title, description, status, priority, created_at, updated_at \
         FROM twitch_roadmap_items ORDER BY priority DESC, id ASC",
    )
    .fetch_all(&pool)
    .await;

    let rows = match rows {
        Ok(rows) => rows,
        Err(e) => {
            tracing::error!("roadmap SELECT fehlgeschlagen: {e}");
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({"error":"DB-Fehler"})),
            )
                .into_response();
        }
    };

    Json(group_rows(rows)).into_response()
}

fn group_rows(rows: Vec<sqlx::postgres::PgRow>) -> serde_json::Value {
    let mut grouped = json!({"planned": [], "in_progress": [], "done": []});
    for row in rows {
        let status = row
            .try_get::<String, _>("status")
            .unwrap_or_else(|_| "planned".to_string());
        let group = if matches!(status.as_str(), "planned" | "in_progress" | "done") {
            status.as_str()
        } else {
            "planned"
        };
        let item = json!({
            "id": row.try_get::<i64, _>("id").unwrap_or(0),
            "title": row.try_get::<String, _>("title").unwrap_or_default(),
            "description": row.try_get::<Option<String>, _>("description").unwrap_or(None),
            "status": status,
            "priority": row.try_get::<i32, _>("priority").unwrap_or(0),
            "created_at": row.try_get::<chrono::DateTime<chrono::Utc>, _>("created_at").ok(),
            "updated_at": row.try_get::<chrono::DateTime<chrono::Utc>, _>("updated_at").ok(),
        });
        grouped[group]
            .as_array_mut()
            .expect("Roadmap-Gruppen sind Arrays")
            .push(item);
    }
    grouped
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::{body::to_bytes, response::IntoResponse};
    use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
    use std::str::FromStr;

    async fn pool() -> Option<PgPool> {
        let dsn = std::env::var("TB_TEST_DATABASE_URL").ok()?;
        let admin = PgPoolOptions::new()
            .max_connections(1)
            .connect(&dsn)
            .await
            .ok()?;
        sqlx::query("DROP SCHEMA IF EXISTS t_roadmap_native CASCADE")
            .execute(&admin)
            .await
            .ok()?;
        sqlx::query("CREATE SCHEMA t_roadmap_native")
            .execute(&admin)
            .await
            .ok()?;
        admin.close().await;
        let options = PgConnectOptions::from_str(&dsn)
            .ok()?
            .options([("search_path", "t_roadmap_native")]);
        PgPoolOptions::new()
            .max_connections(2)
            .connect_with(options)
            .await
            .ok()
    }

    #[tokio::test]
    async fn roadmap_gruppiert_status_und_unbekannt_als_geplant() {
        let Some(pool) = pool().await else { return };
        sqlx::query(ENSURE_TABLE_SQL).execute(&pool).await.unwrap();
        sqlx::query(
            "INSERT INTO twitch_roadmap_items (title, status, priority) VALUES \
             ('Aktiv','in_progress',2),('Fertig','done',1),('Alt','unknown',0)",
        )
        .execute(&pool)
        .await
        .unwrap();

        let response = get_handler(State(pool)).await.into_response();
        assert_eq!(response.status(), StatusCode::OK);
        let body = to_bytes(response.into_body(), usize::MAX).await.unwrap();
        let value: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(value["in_progress"][0]["title"], "Aktiv");
        assert_eq!(value["done"][0]["title"], "Fertig");
        assert_eq!(value["planned"][0]["title"], "Alt");
    }
}
